export const EXAM_CONFIG = {
  examId: "EXAM026",
  slug: "hsk",
  shortSlug: "hsk",
  name: "HSK",
  fullName: "HSK (Hanyu Shuiping Kaoshi)",
  description: "Free HSK practice questions for levels 1–6 with reading, listening, and writing exercises powered by AI analytics.",
  url: "https://hsk.koydo.app",
  category: "Language proficiency",
  subcategory: "Chinese proficiency",
  country: "Global",
  region: "Global",
  languages: ["Chinese"] as const,
  primaryLanguage: "zh",
  sections: ["Reading", "Listening", "Writing"] as const,
  levels: ["HSK 1", "HSK 2", "HSK 3", "HSK 4", "HSK 5", "HSK 6"] as const,
  testFormat: "Paper/computer" as const,
  questionFormat: "MCQ" as const,
  scoring: "Level score" as const,
  themeColor: "#B91C1C",
  themeColorDark: "#991B1B",
  ipRisk: "Medium" as const,
  ipDisclaimer: "HSK is administered by the Center for Language Education and Cooperation (CLEC). Koydo is not affiliated with, endorsed by, or connected to CLEC or any Chinese government agency.",
  freemiumGate: { dailyQuestions: 10 },
  contentReuseCluster: "language_3skills",
  uiEngineProfile: "timed_objective_plus_writing",
} as const;

export type ExamConfig = typeof EXAM_CONFIG;
